// Generated by https://quicktype.io

export interface Post {
    id:          number;
    user:        User;
    categoria:   Categoria;
    title:       string;
    slug:        string;
    description: string;
    content:     string;
    imagen:      string;
    published:   boolean;
    tags:        Tag[];
    anuncios:    Anuncio[];
    created_at:  string;
}

export interface Anuncio {
    id:                number;
    name:              Name;
    image:             string;
    categoria_anuncio: Categoria;
    description:       Description;
    address:           Address;
    phone:             string;
    cellphone:         string;
    status:            number;
    tags:              any[];
    created_at:        CreatedAt;
}

export enum Address {
    ArequipaPerú = "Arequipa, Perú",
    CaliformaEstadosUnidos = "Califorma, Estados Unidos",
    NuevoHorizontePerú = "Nuevo Horizonte, Perú",
}

export interface Categoria {
    id:          number;
    name:        string;
    color:       string;
    description: string;
    created_at:  CreatedAt;
    image?:      string;
}

export enum CreatedAt {
    The260620221924 = "26-06-2022 19:24",
    The260620221937 = "26-06-2022 19:37",
}

export enum Description {
    AliceSoonCameToTheClassicsMasterThough = "Alice soon came to the Classics master, though.",
    IUsedAndIDonTLikeTheThreeWereAll = "I used--and I don't like the three were all.",
    InALittleScreamHalfOfThemAndItBelongs = "In a little scream, half of them--and it belongs.",
}

export enum Name {
    CocaCola = "Coca Cola",
    Oechsle = "Oechsle!",
    PilsenCallao = "Pilsen Callao",
}

export interface Tag {
    id:   number;
    name: string;
}

export interface User {
    id:         number;
    name:       string;
    email:      string;
    rol:        string;
    created_at: CreatedAt;
}
