// Generated by https://quicktype.io

export interface Video {
    id:         number;
    titulo:     string;
    imagen:     string;
    url:        string;
    created_at: string;
    updated_at: string;
}
