// Generated by https://quicktype.io

export interface Anuncios {
    id: number;
    name: string;
    image: string;
    categoria_anuncio: CategoriaAnuncio;
    description: string;
    address: string;
    phone: string;
    cellphone: string;
    status: number;
    tags: Tag[];
    created_at: Date;
}

export interface CategoriaAnuncio {
    id: number;
    name: string;
    color: string;
    description: string;
    created_at: CreatedAt;
}

export enum CreatedAt {
    The080620222340 = "08-06-2022 23:40",
}

export interface Tag {
    id: number;
    name: string;
}
