// Generated by https://quicktype.io

export interface Contact {
    id:         number;
    nombre:     string;
    email:      string;
    telefono:   string;
    mensaje:    string;
    created_at: string;
    updated_at: string;
}
