// Generated by https://quicktype.io

export interface PreInscription {
    id:         number;
    nombres:    string;
    apellidos:  string;
    dni:        string;
    email:      string;
    apoderado:  string;
    telefono:   string;
    nivel:      string;
    grado:      string;
    created_at: string;
    updated_at: string;
}
